version: "3.7"

services:
  app:
    image: node:alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /todo-app
    volumes:
      - /todo-app
    stdin_open: true